# Generated by Django 5.1 on 2024-10-03 15:34

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateField(auto_created=datetime.datetime(2024, 10, 3, 15, 34, 14, 518925))),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images')),
                ('title', models.TextField(max_length=250)),
                ('body', models.TextField()),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
