# Generated by Django 5.1 on 2024-11-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_comment_delete_followercount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
