# Generated by Django 5.1 on 2024-11-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0001_initial'),
        ('core_user', '0002_alter_user_created_at_alter_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post_liked',
            field=models.ManyToManyField(related_name='liked_by', to='core_post.post'),
        ),
    ]
