# Generated by Django 5.1 on 2024-12-10 09:42

import core.post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0002_alter_post_image_alter_post_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.post.models.post_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
